[package]
name = "inversion_api_broker"
version = "0.0.1"
authors = ["neonphog <neonphog@gmail.com>"]
edition = "2018"

[dependencies]
rmp-serde = "0.14"
serde = { version = "1", features = [ "derive" ] }
