[package]
name = "inversion_api_broker"
version = "0.0.1"
authors = ["neonphog <neonphog@gmail.com>"]
edition = "2018"

[dependencies]
nanoid = "0.4"
parking_lot = "0.11.1"
rmp-serde = "0.15"
serde = { version = "1", features = [ "derive", "rc" ] }
